#!/usr/bin/env bash
# ============================================================
# ALTER — INSTALL
# ============================================================
# 1. Checks dependencies
# 2. Backs up any existing configs before touching anything
# 3. Symlinks every module into ~/.config/
# 4. Regenerates hypr/conf/colors.conf from the master token file
# 5. Installs fonts
# ============================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config"
BACKUP_DIR="$HOME/.config-backup-$(date +%Y%m%d_%H%M%S)"

echo "== Alter install =="

# --- 1. Dependency check -------------------------------------------------
DEPS=(hyprland waybar kitty fish starship rofi hyprlock hypridle hyprpaper swaync yazi fastfetch grim slurp wl-copy nmcli)
MISSING=()
for dep in "${DEPS[@]}"; do
    command -v "$dep" >/dev/null 2>&1 || MISSING+=("$dep")
done

if [ "${#MISSING[@]}" -ne 0 ]; then
    echo "Missing dependencies: ${MISSING[*]}"
    echo "Install these with your package manager before continuing (e.g. pacman -S <pkg> on Arch)."
    read -rp "Continue anyway? [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || exit 1
fi

# --- 2. Backup existing configs ------------------------------------------
MODULES=(hypr waybar kitty fish starship rofi hyprlock hypridle hyprpaper swaync gtk qt fastfetch yazi)

mkdir -p "$BACKUP_DIR"
for mod in "${MODULES[@]}"; do
    if [ -e "$CONFIG_DIR/$mod" ] && [ ! -L "$CONFIG_DIR/$mod" ]; then
        echo "Backing up existing $mod -> $BACKUP_DIR/"
        mv "$CONFIG_DIR/$mod" "$BACKUP_DIR/"
    fi
done
echo "Backups (if any) stored at: $BACKUP_DIR"

# --- 3. Symlink modules ----------------------------------------------------
mkdir -p "$CONFIG_DIR"
for mod in "${MODULES[@]}"; do
    rm -rf "$CONFIG_DIR/$mod"
    ln -s "$REPO_DIR/$mod" "$CONFIG_DIR/$mod"
    echo "Linked $mod"
done

# Assets and scripts are shared across modules (wallpapers, fonts, icons,
# and helper scripts invoked by keybinds/waybar), so they're linked
# separately rather than nested under a single module.
rm -rf "$CONFIG_DIR/assets" "$CONFIG_DIR/scripts"
ln -s "$REPO_DIR/assets" "$CONFIG_DIR/assets"
ln -s "$REPO_DIR/scripts" "$CONFIG_DIR/scripts"
chmod +x "$REPO_DIR"/scripts/*.sh
echo "Linked assets and scripts"

# --- 4. Regenerate hypr color mirror from the master token file -----------
# Keeps hypr/conf/colors.conf in sync with assets/themes/colors.conf so
# there's still only ONE place you ever hand-edit a hex value.
TOKENS="$REPO_DIR/assets/themes/colors.conf"
HYPR_COLORS="$REPO_DIR/hypr/conf/colors.conf"

get_token() { grep "^$1=" "$TOKENS" | cut -d= -f2 | awk '{print $1}'; }

cat > "$HYPR_COLORS" <<EOF
# Auto-generated by install.sh from assets/themes/colors.conf — do not edit directly.

\$background     = rgba($(get_token background)ff)
\$panel          = rgba($(get_token panel)ff)
\$card           = rgba($(get_token card)ff)

\$accent         = rgba($(get_token accent)ff)
\$accent_focused = rgba($(get_token accent_focused)ff)
\$accent_hover   = rgba($(get_token accent_hover)ff)

\$text_primary   = rgba($(get_token text_primary)ff)
\$text_secondary = rgba($(get_token text_secondary)ff)
\$text_muted     = rgba($(get_token text_muted)ff)

\$border         = rgba($(get_token border)ff)
\$disabled       = rgba($(get_token disabled)ff)
EOF
echo "Regenerated hypr/conf/colors.conf from master tokens"

# --- 5. Fonts ---------------------------------------------------------------
FONT_DIR="$HOME/.local/share/fonts"
mkdir -p "$FONT_DIR"
cp -rn "$REPO_DIR"/assets/fonts/*/* "$FONT_DIR/" 2>/dev/null || true
fc-cache -f >/dev/null 2>&1 || true
echo "Fonts installed (Inter, JetBrainsMono Nerd Font)"

# --- 6. GTK theme -------------------------------------------------------------
mkdir -p "$CONFIG_DIR/gtk-3.0" "$CONFIG_DIR/gtk-4.0"
ln -sf "$REPO_DIR/gtk/settings.ini" "$CONFIG_DIR/gtk-3.0/settings.ini"
ln -sf "$REPO_DIR/gtk/settings.ini" "$CONFIG_DIR/gtk-4.0/settings.ini"

echo ""
echo "== Install complete =="
echo "Log out and back into Hyprland (or reboot) to apply everything."
echo "If anything looks wrong, your previous configs are safe at: $BACKUP_DIR"
